### ISSUE TITLE
Support custom repositories and  filtering the stable versions ?

### ISSUE THREAD

**Issue by MarkMjw** [tarn2206/gradle-dependencies-checker#7]
Can support custom repositories and filtering stable versions ? many libraries are not publish to the central repository, and a lot of libraries the latest is alpha or beta version.

**Comment by VladDaniliuk** [comment]
Also have same issue. I would like to see possibility (for example switcher) see stable/latest versions separately.

**Comment by VladDaniliuk** [comment]
@MarkMjw , I think, you can close this issue, becouse in new version of this plugin you can add links to repositories and filter versions by stable and unstable.
